[phases.setup]
nixPkgs = ["python311", "git"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
cmd = "gunicorn myProject.wsgi:application --bind 0.0.0.0:$PORT"
